# Generated by Django 5.2.9 on 2026-08-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_new_features_batch2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SEND', 'Send'), ('RECEIVE', 'Receive'), ('SHIFT', 'Shift'), ('EXCHANGE', 'Exchange'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], max_length=10),
        ),
        migrations.DeleteModel(
            name='WebAuthnCredential',
        ),
    ]
